So it has turned out that I don't get what einsum is doing very well. Here is some review practice work:

In [2]:
import numpy as np
import fancy_einsum as einsum

1. repeating letters between input arrays indicate values that, along those axes, will be multiplied together. said products make up the values for the output array

In [74]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 3, 4])

In [75]:
einsum.einsum('i, j -> i j', a, b)

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12]])

write the einsum as a for loop if you don't quite get it!

In [76]:
c = np.zeros((3,4))
for i in range(3):
    for j in range(4):
        total = 0

        total += a[i] * b[j]
        c[i][j] = total

print(c)

[[ 1.  2.  3.  4.]
 [ 2.  4.  6.  8.]
 [ 3.  6.  9. 12.]]


In [78]:
einsum.einsum('i, j -> j i', a, b)

array([[ 1,  2,  3],
       [ 2,  4,  6],
       [ 3,  6,  9],
       [ 4,  8, 12]])

In [77]:
c = np.zeros((4,3))
for j in range(4):
    for i in range(3):
        total = 0
        total += a[i] * b[j]
        c[j][i] = total
print(c)


[[ 1.  2.  3.]
 [ 2.  4.  6.]
 [ 3.  6.  9.]
 [ 4.  8. 12.]]


In [84]:
a = np.array([[1,2,3], [5,6,7]])
b = np.array([4,5,6])

einsum.einsum('x i , i -> x', a, b)

array([32, 92])

In [85]:
c = np.zeros((2))
for x in range(2):
    total = 0
    for i in range(3):
        total += a[x][i] * b[i]
    c[x] = total

print(c)


[32. 92.]


In [87]:
a = np.array([[[1,3],[2,9],[3,4]],
             [[4,5],[9,6],[3,7]]]) # shape (2,3,2)
b = np.array([4,5,6])              # shape (3)

einsum.einsum('i j k, j -> j', a, b)

array([ 52, 130, 102])

In [88]:
c = np.zeros((3))
for j in range(3):
    total = 0
    for i in range(2):
        for k in range(2):
            total += a[i][j][k] * b[j]
    c[j] = total

print(c)

[ 52. 130. 102.]


In [44]:
a = np.array([[1,2,3,4,5],
             [5,6,7,8,9],
             [5,6,7,8,9],
             [5,6,7,8,9]]) # shape (4,5)

b = np.array([[1,2,3,4,5],
             [5,6,7,8,9],
             [5,6,7,8,9],
             [5,6,7,8,9]]) # shape (4,5)

In [46]:
einsum.einsum('i j, i j -> i j', a, b)

array([[ 1,  4,  9, 16, 25],
       [25, 36, 49, 64, 81],
       [25, 36, 49, 64, 81],
       [25, 36, 49, 64, 81]])

2. Omitting a letter from the output means that values along that axis will be summed

In [72]:
a = np.array([[1, 2, 3],
           [2, 2, 2],
           [5, 5, 5]])

b = np.array([[1, 0, 0],
           [1, 1, 0],
           [1, 1, 1]])

In [73]:
einsum.einsum('i j, j k -> i j k', a, b)

array([[[1, 0, 0],
        [2, 2, 0],
        [3, 3, 3]],

       [[2, 0, 0],
        [2, 2, 0],
        [2, 2, 2]],

       [[5, 0, 0],
        [5, 5, 0],
        [5, 5, 5]]])

In [25]:
einsum.einsum('i j, i j -> i', a, b)

array([ 55, 255, 255, 255])

In [26]:
einsum.einsum('i j, i j -> j', a, b)

array([ 76, 112, 156, 208, 268])

In [27]:
einsum.einsum('i j, i j -> ', a, b)

820

In [41]:
einsum.einsum('i j, i k -> j', a, b)

array([168, 204, 240, 276, 312])

In [89]:
a = np.array([[1,2,3,4,5],
             [5,6,7,8,9],
             [5,6,7,8,9],
             [5,6,7,8,9]]) # shape (4,5)

b = np.array([[1,2],
            [3,4],
            [5,6],
            [7,8]]) # shape (4, 2)

In [90]:
c = np.zeros((4,2))
for i in range(4):
    for k in range(2):
        total = 0
        for j in range(5):
            total += a[i][j] * b[i][k]
        c[i][k] = total
print(c)

[[ 15.  30.]
 [105. 140.]
 [175. 210.]
 [245. 280.]]


In [95]:
einsum.einsum("i j, i k-> i j k", a, b)

array([[[ 1,  2],
        [ 2,  4],
        [ 3,  6],
        [ 4,  8],
        [ 5, 10]],

       [[15, 20],
        [18, 24],
        [21, 28],
        [24, 32],
        [27, 36]],

       [[25, 30],
        [30, 36],
        [35, 42],
        [40, 48],
        [45, 54]],

       [[35, 40],
        [42, 48],
        [49, 56],
        [56, 64],
        [63, 72]]])